### ISSUE TITLE
Proposal: read configs from the Environment

### ISSUE THREAD

**Issue by ninowalker** [Livefyre/py-yacc#18]
# Motivation

Not all configuration values can be provided via files on disk. Additionally, the environment is a traditional injection mechanism for spawn-time configuration.

# Use Cases

## Individual values via ENV

Here an individual key within a section is overridden. These values could be of any valid type.

#### Key syntax.
Individual keys be identified via the following transform `"<section>__<key>".replace(/[^a-z0-9_]/_/g)`. Readers should be `case sensitive`.

Examples:
* Section.key -> Section__key
* Section.long-key -> Section__long_key
* Section.long_-key -> Section__long__key

Values should be parsed via the YAML parser; allowing any valid input.

## Provide complete overlay(s) via ENV

There are many cases where managing a bunch of environment variables is tedious at best. Here, one or more environment variables would provide overlays above and beyond the files provided.

The primary use case for multiple env vars is to separate concerns.

#### Default: Single overlay

`py_yacc__config` be used a default environment key to an overlay which will be treated as a document (parsing into a map).

#### Multiple overlays

To support multiple overlays, the key `py_yacc__overlays` can be specified as environment variable; e.g.

```
# in the shell: 
export py_yacc__overlays="['file://env_dev.yaml', 'file:///etc/cluster.yaml', 'env://METHOS_CONFIG']"
```

These will be parsed, in order, and env vars must be treated as optional; e.g. `{} if envvar not in os.environ`

#### Environment Variable Value Parsing

Environment variable values will be parsed by interpreted as raw YAML by default. Additionally, parsers should recognize data URIs in the form:

```
data:application/yaml,{foo: {bar: baz}}
data:application/yaml;base64,dmxhZGltaXI6IHt0eXBlOiB2YXVsdH0K
data:application/yaml;charset=utf-8;base64,dmxhZGltaXI6IHt0eXBlOiB2YXVsdH0K
```

The parser may support other mimetypes (application/json), but that is discretionary.

**Comment by andrewguy9** [comment]
> These will be parsed, in order, and env vars must be treated as optional; e.g. {} if envvar not in `os.environ`
This is in contrast to file overlays, which fail of not present. Should we make them behave the same?

**Comment by andrewguy9** [comment]
```
# in a file
py-yacc:
  overlays: ["file://somewhere/some.yaml", ENVVAR_NAME1, ENVVAR_NAME2]
```

This could get meta quickly. What if one overlay specified another overlay? 

I would rather keep overlay definition outside of the configs, and specify that in the invocation of pyyacc. You could keep the `ENVVAR` overlay concept with something like
`pyyacc (<yaml>|--var <envvar>) ...`

**Comment by andrewguy9** [comment]
I didn't understand the section "Individual values via ENV".
Your goal is to replace a config value, by looking at the `ENVVAR`s and replacing config knobs. 

But your example transform (`"<section>__<key>".replace(/[^a-z0-9_]/_/g`). goes from objects to shell names. 

Do you want to go from shell names to keys?

**Comment by ninowalker** [comment]
@andrewguy9 

> This is in contrast to file overlays, which fail of not present. Should we make them behave the same?

I think you are probably right. If `env_methos57_aws.yaml` is not present, we can ignore it. It's fair to assume the full overlay would be provided via an environment var in that case.

> This could get meta quickly. What if one overlay specified another overlay?

Agreed; perhaps we only support this as an env var (and make `file://` implicit): `export py_yacc__overlays="['env_dev.yaml', '/etc/cluster.yaml', 'env://METHOS_CONFIG']"`

> But your example transform ... goes from objects to shell names.

Yes; this is evaluated in the values resolution phase where we flatten the maps. We'd probe the env for the matching key at that point.

**Comment by ninowalker** [comment]
This was complete with pyyacc3
