### ISSUE TITLE
Proposal: support flat section/keys in overlays

### ISSUE THREAD

**Issue by ninowalker** [Livefyre/py-yacc#19]
# Simpler overlay files

Most overlays indicate just one or two values in a section. To increase usability, the config resolver should handle a concise form `<section>.<key>: <value>` as equivalent to `section: {key: value}`. 

```
environment.type: dev
application.number_of_threads: 5
```

## Special Cases

If both are present in the SAME overlay, the config resolver should raise an error. There is not issue if the key is respecified in a later scenario.

```
# error scenario
environment:
  type: dev

environment.type: meow
```

**Comment by matt-livefyre** [comment]
not sure i see the utility here, especially considering this appears to necessitate an additional parsing step (with a custom parser). if i'm mistaken, perhaps you could elaborate.

**Comment by andrewguy9** [comment]
+1 - Could make configs shorter.
-1 - Will make yaml configs even harder to parse. 

I could go either way.

**Comment by ninowalker** [comment]
@matt-livefyre I don't think this requires a custom parser, just customization. From an implementation perspective, it's pretty simple. Overlays are parsed into maps, which happen to have nested maps. During the resolution phase, for each key in a section, you check if the section and key are present in the overlay (because maps are merged). In this case you'd just add the check if "section.key" is present in the map.

**Comment by ninowalker** [comment]
From a utility perspective, it's sugar :)

**Comment by ninowalker** [comment]
Withdrawing this proposal for now. Focusing on others.
