### ISSUE TITLE
Py-yacc should produce INI files. 

### ISSUE THREAD

**Issue by andrewguy9** [Livefyre/py-yacc#21]

**Comment by ninowalker** [comment]
@andrewguy9 are you thinking configparser style?

```
[environment]
type = qa

[cat]
sound = meow
```

**Comment by andrewguy9** [comment]
I'm not familiar with configparser, but it looks like they support old school ini (i.e. no Windows Registry features). That seems fine to me.

I think our goal should be to render MySQL and Mongo configs via PYYACC.

Today we only use PYYACC for our apps, so our Mongo / MySQL / Kafka puppet config management has to duplicate a bunch of functionality and is a source of bugs. It would be great if PYYACC could prevent us from pushing bad MySQL config! 😀

**Comment by ninowalker** [comment]
INI format is supported.
